#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Static growth surfaces, regenerated by the pipeline on every data commit.

The app is a JS-only SPA = ONE indexable URL in a SERP with 7+ Lithuanian
fuel-price competitors, and AI crawlers that respect robots.txt see an empty
shell. This script turns the committed stations.json into crawlable HTML:

  kainos/<municipality-slug>.html   ~60 landing pages: today's min/avg/max for
                                    the municipality + its cheapest-10 table,
                                    ItemList/GasStation JSON-LD, canonical,
                                    link into the app pre-filtered to the muni.
  kainos/index.html                 the directory of all municipality pages.
  sitemap.xml                       homepage + all pages, lastmod = data date.
  index.html                        two marker blocks refreshed in place:
                                    a static human-readable price block (what
                                    JS-less crawlers read; the app repaints it
                                    live on boot) and the meta descriptions.

Pure local-file work (no network) — safe to run in every pipeline pass.
"""

import datetime as dt
import html
import json
import os
import math
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lt_places import place

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8")
    except Exception:
        pass

SITE = "https://fuelis.lt"
OUTDIR = "kainos"
FUELS = [("petrol95", "Benzinas 95"), ("diesel", "Dyzelinas"), ("lpg", "Dujos (LPG)")]

_DEACC = str.maketrans("ąčęėįšųūžĄČĘĖĮŠŲŪŽ", "aceeisuuzACEEISUUZ")


def slugify(muni):
    s = muni.translate(_DEACC).lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


def esc(s):
    return html.escape(str(s or ""), quote=True)


def fmt(v):
    return f"€{v:.3f}" if isinstance(v, (int, float)) else "–"


def muni_stats(rows):
    out = {}
    for key, _ in FUELS:
        vals = [s[key] for s in rows if isinstance(s.get(key), (int, float))]
        if vals:
            out[key] = {"min": min(vals), "avg": sum(vals) / len(vals), "max": max(vals), "n": len(vals)}
    return out


PAGE_CSS = """body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;margin:0;background:#f4f6fa;color:#1b2430}
.wrap{max-width:860px;margin:0 auto;padding:18px 14px 40px}
a{color:#0062CC}.card{background:#fff;border:1px solid #e2e6ec;border-radius:12px;padding:16px;margin:14px 0}
h1{font-size:22px;margin:10px 0 2px}h2{font-size:16px;margin:0 0 10px}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{padding:7px 8px;text-align:left;border-bottom:1px solid #eef1f4}th{color:#55606d;font-weight:600}
td.n{font-variant-numeric:tabular-nums;white-space:nowrap}.lo{color:#15803d;font-weight:700}
.meta{color:#6b7280;font-size:12.5px}.cta{display:inline-block;background:#0062CC;color:#fff;padding:11px 18px;
border-radius:10px;text-decoration:none;font-weight:600;margin-top:6px}
.bc{font-size:12.5px;color:#6b7280;margin-bottom:4px}.bc a{color:#6b7280}
.nb{margin:0;padding-left:18px;font-size:14px;line-height:1.7}
.grid{display:flex;flex-wrap:wrap;gap:8px}.grid a{background:#fff;border:1px solid #e2e6ec;border-radius:10px;
padding:9px 13px;text-decoration:none;font-size:14px}"""


def page_shell(title, desc, canonical, body, jsonld=None):
    ld = f'<script type="application/ld+json">{json.dumps(jsonld, ensure_ascii=False)}</script>' if jsonld else ""
    return f"""<!DOCTYPE html>
<html lang="lt">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="canonical" href="{canonical}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{canonical}">
<meta property="og:image" content="{SITE}/og-image.png">
<meta name="robots" content="index, follow">
{ld}
<style>{PAGE_CSS}</style>
</head>
<body><div class="wrap">{body}</div></body>
</html>"""


def centroid(rows):
    pts = [(r["lat"], r["lon"]) for r in rows
           if isinstance(r.get("lat"), (int, float)) and isinstance(r.get("lon"), (int, float))]
    if not pts:
        return None
    return (sum(p[0] for p in pts) / len(pts), sum(p[1] for p in pts) / len(pts))


def km(a, b):
    dlat = (a[0] - b[0]) * 111.0
    dlon = (a[1] - b[1]) * 111.0 * math.cos(math.radians((a[0] + b[0]) / 2))
    return math.hypot(dlat, dlon)


def plural(n, one, few, many):
    """Lithuanian numeral agreement: 1/21/31 -> singular, 2-9/22-29 -> plural
    nominative, 0 and 10-19 -> genitive plural. ("1 degalinės" is wrong.)"""
    if n % 10 == 1 and n % 100 != 11:
        return one
    if 2 <= n % 10 <= 9 and not (11 <= n % 100 <= 19):
        return few
    return many


def priced_rows(rows):
    """Stations that actually carry a price — the only ones the tables can show.
    The headline count MUST use this too: 36 of 60 pages previously announced a
    total that included price-less registry stations and then contradicted
    themselves two lines below."""
    return [r for r in rows if any(isinstance(r.get(k), (int, float))
                                   for k in ("petrol95", "diesel", "lpg"))]


def cheapest_rows(rows, limit=10):
    """Rank by diesel, then by petrol for stations that sell no diesel — the old
    version silently DROPPED every diesel-less station (17 of 60 municipalities)
    while the heading still promised '10 pigiausių'."""
    def key(r):
        d = r.get("diesel"); p = r.get("petrol95")
        return (0 if isinstance(d, (int, float)) else 1,
                d if isinstance(d, (int, float)) else (p if isinstance(p, (int, float)) else 9e9))
    return sorted(priced_rows(rows), key=key)[:limit]


def build_muni_page(muni, rows, updated, neighbours=()):
    slug = slugify(muni)
    stats = muni_stats(rows)
    if not stats:
        return None
    name, loc = place(muni)          # "Kaunas" / "Kaune" — what people search
    priced = priced_rows(rows)
    n = len(priced)

    title = f"Degalų kainos {loc} — pigiausios degalinės | Fuelis"
    d_avg = stats.get("diesel", {}).get("avg")
    p_avg = stats.get("petrol95", {}).get("avg")
    desc = (f"Degalų kainos {loc} ({updated}), oficialūs LEA duomenys iš {n} degalinių. "
            + (f"Dyzelinas vid. {fmt(d_avg)}, " if d_avg else "")
            + (f"benzinas 95 vid. {fmt(p_avg)}. " if p_avg else "")
            + "Pigiausių degalinių sąrašas ir žemėlapis.")

    stat_rows = "".join(
        f"<tr><td>{label}</td><td class='n lo'>{fmt(s['min'])}</td>"
        f"<td class='n'>{fmt(s['avg'])}</td><td class='n'>{fmt(s['max'])}</td><td class='n'>{s['n']}</td></tr>"
        for key, label in FUELS if (s := stats.get(key)))

    cheapest = cheapest_rows(rows)
    cheap_rows = "".join(
        f"<tr><td>{esc(r.get('network'))}</td><td>{esc(r.get('address'))}</td>"
        f"<td class='n'>{fmt(r.get('petrol95'))}</td><td class='n'>{fmt(r.get('diesel'))}</td>"
        f"<td class='n'>{fmt(r.get('lpg'))}</td></tr>" for r in cheapest)
    # Honest heading: say what the table actually shows.
    c = len(cheapest)
    cheap_title = (f"Visos degalinės ({c})" if c >= n and c > 1 else
                   "Vienintelė degalinė" if c == 1 else
                   f"{c} " + plural(c, "pigiausia degalinė", "pigiausios degalinės", "pigiausių degalinių"))

    # schema.org ItemList is an Intangible — it has NO dateModified property
    # (the old markup emitted one, which fails validation); the date is visible
    # in the page text instead.
    jsonld = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": f"Pigiausios degalinės — {name}",
        "numberOfItems": len(cheapest),
        "itemListElement": [{
            "@type": "ListItem", "position": i + 1,
            "item": {"@type": "GasStation", "name": r.get("network") or "Degalinė",
                     "address": {"@type": "PostalAddress", "streetAddress": r.get("address") or "",
                                 "addressLocality": name, "addressCountry": "LT"}}
        } for i, r in enumerate(cheapest)],
    }

    # Neighbouring municipalities: genuine added value (where to drive if local
    # prices are bad) AND the internal linking the cluster completely lacked.
    nb = "".join(
        f'<li><a href="{SITE}/kainos/{slugify(m)}.html">{esc(place(m)[0])}</a>'
        f' — dyzelinas nuo {fmt(v)}{"" if d is None else f" ({d:.0f} km)"}</li>'
        for m, v, d in neighbours)
    nb_block = (f'<div class="card"><h2>Kaimyninės savivaldybės</h2><ul class="nb">{nb}</ul>'
                f'<p class="meta">Jei kainos {loc} aukštos, gretimose savivaldybėse gali būti pigiau.</p></div>'
                if nb else "")

    app_url = f"{SITE}/?muni={muni.replace(' ', '%20')}"
    body = f"""<p class="bc"><a href="{SITE}/">Fuelis</a> › <a href="{SITE}/kainos/">Kainos pagal savivaldybę</a> › {esc(name)}</p>
<h1>Degalų kainos {esc(loc)}</h1>
<p class="meta">Oficialūs LEA (ena.lt) duomenys · atnaujinta {updated} · {n} {plural(n, "degalinė", "degalinės", "degalinių")} su kainomis · {esc(muni)}</p>
<div class="card"><h2>Kainų suvestinė</h2>
<table><thead><tr><th></th><th>Pigiausia</th><th>Vidurkis</th><th>Brangiausia</th><th>Degalinių</th></tr></thead>
<tbody>{stat_rows}</tbody></table></div>
<div class="card"><h2>{cheap_title}</h2>
<table><thead><tr><th>Tinklas</th><th>Adresas</th><th>95</th><th>Dyzelinas</th><th>LPG</th></tr></thead>
<tbody>{cheap_rows}</tbody></table>
<p class="meta">Rikiuota pagal dyzeliną; degalinės be dyzelino rodomos pagal benziną. Kainos — LEA
dienos suvestinė, dienos eigoje degalinėse gali keistis.</p>
<a class="cta" href="{app_url}">Atidaryti žemėlapyje →</a></div>
{nb_block}
<p class="meta">Visos savivaldybės: <a href="{SITE}/kainos/">kainos pagal savivaldybę</a> ·
<a href="{SITE}/">Fuelis — degalų kainų žemėlapis</a></p>"""
    return slug, page_shell(title, desc, f"{SITE}/kainos/{slug}.html", body, jsonld)


def build_directory(slugs_munis, updated):
    links = "".join(f'<a href="{SITE}/kainos/{slug}.html">{esc(place(muni)[0])}</a>'
                    for slug, muni in sorted(slugs_munis, key=lambda x: place(x[1])[0]))
    body = f"""<p class="bc"><a href="{SITE}/">Fuelis</a> › Kainos pagal savivaldybę</p>
<h1>Degalų kainos pagal miestus ir savivaldybes</h1>
<p class="meta">Oficialūs LEA duomenys · atnaujinta {updated}</p>
<div class="card"><div class="grid">{links}</div></div>
<p class="meta"><a href="{SITE}/">← Fuelis žemėlapis ir paieška</a> ·
<a href="{SITE}/atviri-duomenys.html">Atviri duomenys (JSON/CSV API)</a></p>"""
    return page_shell("Degalų kainos pagal savivaldybę | Fuelis",
                      f"Oficialios degalų kainos visose Lietuvos savivaldybėse ({updated}): benzinas 95, dyzelinas, dujos.",
                      f"{SITE}/kainos/", body)


def build_sitemap(slugs, updated):
    urls = [f"{SITE}/", f"{SITE}/kainos/", f"{SITE}/atviri-duomenys.html",
            f"{SITE}/privatumas.html"]
    urls += [f"{SITE}/kainos/{s}.html" for s in sorted(slugs)]
    entries = "\n".join(
        f"  <url>\n    <loc>{u}</loc>\n    <lastmod>{updated}</lastmod>\n"
        f"    <changefreq>daily</changefreq>\n    <priority>{'1.0' if u.endswith('.lt/') else '0.7'}</priority>\n  </url>"
        for u in urls)
    return f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{entries}\n</urlset>\n'


def refresh_index_html(summary, updated, n_stations):
    """Rewrite the two marker blocks in index.html in place (idempotent)."""
    p = "index.html"
    s = open(p, encoding="utf-8").read()
    avg = lambda k: (summary.get(k) or {}).get("avg")
    parts = []
    if avg("diesel"): parts.append(f"dyzelinas vid. €{avg('diesel'):.3f}")
    if avg("petrol95"): parts.append(f"benzinas 95 vid. €{avg('petrol95'):.3f}")
    if avg("lpg"): parts.append(f"dujos €{avg('lpg'):.3f}")
    line = ", ".join(parts)

    desc = (f"Oficialios degalų kainos {n_stations} Lietuvos degalinių ({updated}): {line}. "
            f"Pigiausių ir arčiausių paieška, žemėlapis, EV įkrovimas.")
    s = re.sub(r'(<meta name="description" content=")[^"]*(")', lambda m: m.group(1) + esc(desc) + m.group(2), s)
    s = re.sub(r'(<meta property="og:description" content=")[^"]*(")', lambda m: m.group(1) + esc(desc) + m.group(2), s)
    s = re.sub(r'(<meta name="twitter:description" content=")[^"]*(")', lambda m: m.group(1) + esc(desc) + m.group(2), s)

    block = (f'<!-- FUELIS:STATIC-PRICES --><div class="crawl-prices" id="crawl-prices">'
             f'<p>Atnaujinta {updated}: {esc(line)} — {n_stations} degalinės. '
             f'<a href="{SITE}/kainos/">Kainos pagal savivaldybę</a> · '
             # The homepage is the ONE page Google reliably crawls, so every page
             # we want discovered has to be reachable from this block.
             f'<a href="{SITE}/atviri-duomenys.html">Atviri duomenys (API)</a>.'
             f'</p></div><!-- /FUELIS:STATIC-PRICES -->')
    if "FUELIS:STATIC-PRICES" in s:
        s = re.sub(r'<!-- FUELIS:STATIC-PRICES -->.*?<!-- /FUELIS:STATIC-PRICES -->', block, s, flags=re.S)
    else:
        s = s.replace('<div id="list-view">', block + '\n\n        <div id="list-view">')
    open(p, "w", encoding="utf-8", newline="\n").write(s)


def main():
    d = json.load(open("data/stations.json", encoding="utf-8"))
    updated = d.get("updated") or dt.date.today().isoformat()
    stations = d.get("stations") or []
    by_muni = {}
    for s in stations:
        m = s.get("municipality")
        if m:
            by_muni.setdefault(m, []).append(s)

    os.makedirs(OUTDIR, exist_ok=True)
    # Nearest municipalities by station centroid — powers the cross-links.
    cents = {m: centroid(r) for m, r in by_muni.items()}
    best_diesel = {}
    for m, r in by_muni.items():
        vals = [x["diesel"] for x in r if isinstance(x.get("diesel"), (int, float))]
        if vals:
            best_diesel[m] = min(vals)

    def neighbours_of(muni):
        c = cents.get(muni)
        if not c:
            return []
        near = sorted(((km(c, cents[o]), o) for o in by_muni
                       if o != muni and cents.get(o) and o in best_diesel),
                      key=lambda t: t[0])[:5]
        return [(o, best_diesel[o], d) for d, o in near]

    slugs_munis = []
    for muni, rows in by_muni.items():
        built = build_muni_page(muni, rows, updated, neighbours_of(muni))
        if not built:
            continue
        slug, html_page = built
        open(os.path.join(OUTDIR, f"{slug}.html"), "w", encoding="utf-8", newline="\n").write(html_page)
        slugs_munis.append((slug, muni))
    open(os.path.join(OUTDIR, "index.html"), "w", encoding="utf-8", newline="\n").write(
        build_directory(slugs_munis, updated))
    open("sitemap.xml", "w", encoding="utf-8", newline="\n").write(
        build_sitemap([s for s, _ in slugs_munis], updated))
    refresh_index_html(d.get("summary") or {}, updated, len(stations))
    print(f"[ok] built {len(slugs_munis)} municipality pages + directory + sitemap; index.html refreshed")


if __name__ == "__main__":
    main()
